config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :beer_clubs
  resources :memberships
  resources :users do
    post 'toggle_lock', on: :member
  end

  resource :session, only: [:new, :create, :destroy]

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end

  resources :ratings, only: [:index, :new, :create, :destroy]

  resources :places, only:[:index, :show]
  post 'places', to:'places#search'

  root 'breweries#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  include RatingAverage

  validates :username, uniqueness: true,
                       length: { minimum: 3, maximum: 15 }

  validates :password, length: { minimum: 4 },
                       format: {
                          with: /\d.*[A-Z]|[A-Z].*\d/,
                          message: "has to contain one number and one upper case letter"
                       }

  has_many :ratings, dependent: :destroy
  has_many :beers, through: :ratings
  has_many :memberships
  has_many :beer_clubs, through: :memberships

  has_secure_password

  def self.top(n)
    sorted = User.all.sort_by{ |b| -b.ratings.count }
    sorted[0, n]
  end

  def favorite_beer
    return nil if ratings.empty?
    ratings.order(score: :desc).limit(1).first.beer
  end

  def favorite_style
    favorite :style
  end

  def favorite_brewery
    favorite :brewery
  end

  def favorite(category)
    return nil if ratings.empty?

    rated = ratings.map{ |r| r.beer.send(category) }.uniq
    rated.sort_by { |item| -rating_of(category, item) }.first
  end

  def rating_of(category, item)
    ratings_of = ratings.select{ |r| r.beer.send(category)==item }
    ratings_of.map(&:score).inject(&:+) / ratings_of.count.to_f
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if user_params[:username].nil? and current_user == @user and @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if current_user == @user
      @user.destroy
      #session[:user_id] = nil
    end
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_lock
    user = User.find(params[:id])
    user.update_attribute :locked, (not user.locked)

    new_status = user.locked? ? "unlocked" : "locked"

    redirect_to :back, notice:"user account #{new_status}"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @user.new_record? %>
    <div class="field">
      <%= f.label :username %><br />
      <%= f.text_field :username %>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Change password for <%= @user.username %> </h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table class="table table-hover">
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td>
          <%= link_to user.username, user %>
        </td>
        <td>
          <% if admin_user and user.locked? %>
            <span class="label label-info">account frozen</span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h2>
  <%= @user.username %>
  <% if admin_user and @user.locked? %>
      <span class="label label-info">account frozen</span>
  <% end %>
</h2>

<p>
  Has made <%= pluralize(@user.ratings.count, 'rating') %>
</p>

<% if @user.ratings.any? %>
  <dl class="dl-horizontal">
    <dt>favorite beer<dt>
    <dd><%= @user.favorite_beer.name %></dd>
    <dt>preferred style<dt>
    <dd><%= @user.favorite_style.name %></dd>
    <dt>favorite brewery<dt>
    <dd><%= @user.favorite_brewery.name %></dd>
  </dl>
<% end %>

<% if @user.beer_clubs.any? %>
  <p>
    Member of
    <% @user.beer_clubs.each do |club| %>
      <%= link_to club.name, club %>
    <% end %>
  </p>
<% else %>
  <p>No club memberships</p>
<% end %>

<h3>Ratings</h3>

<ul>
  <% @user.ratings.each do |rating| %>
    <li>
      <%= rating %>
      <% if @user == current_user %>
<%= link_to '', rating, method: :delete, data: { confirm: 'Are you sure?' }, class:'glyphicon glyphicon-trash' %>


      <% end %>
    </li>
  <% end %>
</ul>

<% if @user == current_user %>
  <%= link_to 'Delete account', @user, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %>
  <%= link_to 'Change password', edit_user_path(@user), class:'btn btn-warning' %>
<% end %>

<% if admin_user %>
  <% label = @user.locked? ? 'unlock' : 'lock' %>
  <%= link_to label, toggle_lock_user_path(@user.id), method: :post, class: "btn btn-primary"
  %>
<% end %>